//
//  AuditorySustainFactoryGameSequence(p: .Icon_auditory, s: .swift
//  ECAB
//
//  Created by Raphaël Bertin on 13/07/2016GameSequence(p: .Icon_auditory, s: .
//  Copyright © 2016 Oliver Braddick and Jan AtkinsonGameSequence(p: .Icon_auditory, s: . All rights reservedGameSequence(p: .Icon_auditory, s: .
//

import Foundation

class AuditorySustainFactory {
    
    static let practiceSequence: [GameSequence] =
        [
            GameSequence(p: .Icon_auditory, s: .Bus),
            GameSequence(p: .Icon_auditory, s: .Train),
            GameSequence(p: .Icon_auditory, s: .Ball),
            GameSequence(p: .Icon_auditory, s: .Cat),
            GameSequence(p: .Icon_auditory, s: .Shoe),
            GameSequence(p: .Icon_auditory, s: .Star),
            GameSequence(p: .Icon_auditory, s: .Door),
            GameSequence(p: .Icon_auditory, s: .Car),
            GameSequence(p: .Icon_auditory, s: .Pig),
            GameSequence(p: .Icon_auditory, s: .Sock),
            //GameSequence(p: .Icon_auditory, s: .EndOfPractice),
            //GameSequence(p: .Icon_auditory, s: .Practice1),
            GameSequence(p: .Icon_auditory, s: .Boat),
            GameSequence(p: .Icon_auditory, s: .Spoon),
            GameSequence(p: .Icon_auditory, s: .Sock),
            GameSequence(p: .Icon_auditory, s: .Horse),
            GameSequence(p: .Icon_auditory, s: .Leaf),
            GameSequence(p: .Icon_auditory, s: .Book),
            GameSequence(p: .Icon_auditory, s: .Bus),
            GameSequence(p: .Icon_auditory, s: .Train),
            GameSequence(p: .Icon_auditory, s: .Dog),
            GameSequence(p: .Icon_auditory, s: .Star),
            GameSequence(p: .Icon_auditory, s: .Cake),
            GameSequence(p: .Icon_auditory, s: .Key),
            GameSequence(p: .Icon_auditory, s: .Fish),
            GameSequence(p: .Icon_auditory, s: .Ball),
            GameSequence(p: .Icon_auditory, s: .Tree),
        ]

    static let gameSequence: [GameSequence] =
        [
            GameSequence(p: .Icon_auditory, s: .Train),
            GameSequence(p: .Icon_auditory, s: .Bike),
            GameSequence(p: .Icon_auditory, s: .Star),
            GameSequence(p: .Icon_auditory, s: .Sock),
            GameSequence(p: .Icon_auditory, s: .Fish),
            GameSequence(p: .Icon_auditory, s: .Clock),
            GameSequence(p: .Icon_auditory, s: .Door),
            GameSequence(p: .Icon_auditory, s: .Shoe),
            GameSequence(p: .Icon_auditory, s: .Chair),
            GameSequence(p: .Icon_auditory, s: .Boat),
            GameSequence(p: .Icon_auditory, s: .Pig),
            GameSequence(p: .Icon_auditory, s: .Bed),
            GameSequence(p: .Icon_auditory, s: .Sun),
            GameSequence(p: .Icon_auditory, s: .Key),
            GameSequence(p: .Icon_auditory, s: .Cat),
            GameSequence(p: .Icon_auditory, s: .Bus),
            GameSequence(p: .Icon_auditory, s: .Spoon),
            GameSequence(p: .Icon_auditory, s: .Horse),
            GameSequence(p: .Icon_auditory, s: .Cake),
            GameSequence(p: .Icon_auditory, s: .Car),
            GameSequence(p: .Icon_auditory, s: .Ball),
            GameSequence(p: .Icon_auditory, s: .Tree),
            GameSequence(p: .Icon_auditory, s: .Dog),
            GameSequence(p: .Icon_auditory, s: .Book),
            GameSequence(p: .Icon_auditory, s: .Leaf),
            GameSequence(p: .Icon_auditory, s: .Train),
            GameSequence(p: .Icon_auditory, s: .Horse),
            GameSequence(p: .Icon_auditory, s: .Shoe),
            GameSequence(p: .Icon_auditory, s: .Bed),
            GameSequence(p: .Icon_auditory, s: .Ball),
            GameSequence(p: .Icon_auditory, s: .Chair),
            GameSequence(p: .Icon_auditory, s: .Sock),
            GameSequence(p: .Icon_auditory, s: .Pig),
            GameSequence(p: .Icon_auditory, s: .Book),
            GameSequence(p: .Icon_auditory, s: .Sun),
            GameSequence(p: .Icon_auditory, s: .Boat),
            GameSequence(p: .Icon_auditory, s: .Dog),
            GameSequence(p: .Icon_auditory, s: .Key),
            GameSequence(p: .Icon_auditory, s: .Leaf),
            GameSequence(p: .Icon_auditory, s: .Spoon),
            GameSequence(p: .Icon_auditory, s: .Clock),
            GameSequence(p: .Icon_auditory, s: .Bike),
            GameSequence(p: .Icon_auditory, s: .Fish),
            GameSequence(p: .Icon_auditory, s: .Car),
            GameSequence(p: .Icon_auditory, s: .Door),
            GameSequence(p: .Icon_auditory, s: .Cake),
            GameSequence(p: .Icon_auditory, s: .Bus),
            GameSequence(p: .Icon_auditory, s: .Cat),
            GameSequence(p: .Icon_auditory, s: .Tree),
            GameSequence(p: .Icon_auditory, s: .Star),
            GameSequence(p: .Icon_auditory, s: .Tree),
            GameSequence(p: .Icon_auditory, s: .Cake),
            GameSequence(p: .Icon_auditory, s: .Dog),
            GameSequence(p: .Icon_auditory, s: .Train),
            GameSequence(p: .Icon_auditory, s: .Star),
            GameSequence(p: .Icon_auditory, s: .Shoe),
            GameSequence(p: .Icon_auditory, s: .Pig),
            GameSequence(p: .Icon_auditory, s: .Bus),
            GameSequence(p: .Icon_auditory, s: .Door),
            GameSequence(p: .Icon_auditory, s: .Spoon),
            GameSequence(p: .Icon_auditory, s: .Chair),
            GameSequence(p: .Icon_auditory, s: .Ball),
            GameSequence(p: .Icon_auditory, s: .Sock),
            GameSequence(p: .Icon_auditory, s: .Horse),
            GameSequence(p: .Icon_auditory, s: .Leaf),
            GameSequence(p: .Icon_auditory, s: .Bed),
            GameSequence(p: .Icon_auditory, s: .Car),
            GameSequence(p: .Icon_auditory, s: .Key),
            GameSequence(p: .Icon_auditory, s: .Clock),
            GameSequence(p: .Icon_auditory, s: .Cat),
            GameSequence(p: .Icon_auditory, s: .Boat),
            GameSequence(p: .Icon_auditory, s: .Bike),
            GameSequence(p: .Icon_auditory, s: .Sun),
            GameSequence(p: .Icon_auditory, s: .Book),
            GameSequence(p: .Icon_auditory, s: .Fish),
            GameSequence(p: .Icon_auditory, s: .Chair),
            GameSequence(p: .Icon_auditory, s: .Leaf),
            GameSequence(p: .Icon_auditory, s: .Clock),
            GameSequence(p: .Icon_auditory, s: .Dog),
            GameSequence(p: .Icon_auditory, s: .Bike),
            GameSequence(p: .Icon_auditory, s: .Spoon),
            GameSequence(p: .Icon_auditory, s: .Book),
            GameSequence(p: .Icon_auditory, s: .Ball),
            GameSequence(p: .Icon_auditory, s: .Fish),
            GameSequence(p: .Icon_auditory, s: .Bus),
            GameSequence(p: .Icon_auditory, s: .Key),
            GameSequence(p: .Icon_auditory, s: .Star),
            GameSequence(p: .Icon_auditory, s: .Pig),
            GameSequence(p: .Icon_auditory, s: .Door),
            GameSequence(p: .Icon_auditory, s: .Train),
            GameSequence(p: .Icon_auditory, s: .Sock),
            GameSequence(p: .Icon_auditory, s: .Sun),
            GameSequence(p: .Icon_auditory, s: .Car),
            GameSequence(p: .Icon_auditory, s: .Shoe),
            GameSequence(p: .Icon_auditory, s: .Cat),
            GameSequence(p: .Icon_auditory, s: .Bed),
            GameSequence(p: .Icon_auditory, s: .Boat),
            GameSequence(p: .Icon_auditory, s: .Tree),
            GameSequence(p: .Icon_auditory, s: .Horse),
            GameSequence(p: .Icon_auditory, s: .Cake),
            GameSequence(p: .Icon_auditory, s: .Sock),
            GameSequence(p: .Icon_auditory, s: .Bike),
            GameSequence(p: .Icon_auditory, s: .Cake),
            GameSequence(p: .Icon_auditory, s: .Pig),
            GameSequence(p: .Icon_auditory, s: .Shoe),
            GameSequence(p: .Icon_auditory, s: .Tree),
            GameSequence(p: .Icon_auditory, s: .Car),
            GameSequence(p: .Icon_auditory, s: .Train),
            GameSequence(p: .Icon_auditory, s: .Boat),
            GameSequence(p: .Icon_auditory, s: .Fish),
            GameSequence(p: .Icon_auditory, s: .Leaf),
            GameSequence(p: .Icon_auditory, s: .Bus),
            GameSequence(p: .Icon_auditory, s: .Chair),
            GameSequence(p: .Icon_auditory, s: .Horse),
            GameSequence(p: .Icon_auditory, s: .Clock),
            GameSequence(p: .Icon_auditory, s: .Ball),
            GameSequence(p: .Icon_auditory, s: .Key),
            GameSequence(p: .Icon_auditory, s: .Star),
            GameSequence(p: .Icon_auditory, s: .Cat),
            GameSequence(p: .Icon_auditory, s: .Spoon),
            GameSequence(p: .Icon_auditory, s: .Bed),
            GameSequence(p: .Icon_auditory, s: .Door),
            GameSequence(p: .Icon_auditory, s: .Dog),
            GameSequence(p: .Icon_auditory, s: .Book),
            GameSequence(p: .Icon_auditory, s: .Sun),
            GameSequence(p: .Icon_auditory, s: .Door),
            GameSequence(p: .Icon_auditory, s: .Leaf),
            GameSequence(p: .Icon_auditory, s: .Horse),
            GameSequence(p: .Icon_auditory, s: .Clock),
            GameSequence(p: .Icon_auditory, s: .Key),
            GameSequence(p: .Icon_auditory, s: .Star),
            GameSequence(p: .Icon_auditory, s: .Dog),
            GameSequence(p: .Icon_auditory, s: .Chair),
            GameSequence(p: .Icon_auditory, s: .Bike),
            GameSequence(p: .Icon_auditory, s: .Ball),
            GameSequence(p: .Icon_auditory, s: .Cake),
            GameSequence(p: .Icon_auditory, s: .Spoon),
            GameSequence(p: .Icon_auditory, s: .Train),
            GameSequence(p: .Icon_auditory, s: .Pig),
            GameSequence(p: .Icon_auditory, s: .Book),
            GameSequence(p: .Icon_auditory, s: .Sun),
            GameSequence(p: .Icon_auditory, s: .Fish),
            GameSequence(p: .Icon_auditory, s: .Car),
            GameSequence(p: .Icon_auditory, s: .Boat),
            GameSequence(p: .Icon_auditory, s: .Bus),
            GameSequence(p: .Icon_auditory, s: .Shoe),
            GameSequence(p: .Icon_auditory, s: .Bed),
            GameSequence(p: .Icon_auditory, s: .Cat),
            GameSequence(p: .Icon_auditory, s: .Sock),
            GameSequence(p: .Icon_auditory, s: .Tree),
    ]
}
