//
//  VisualSustainFactory.swift
//  ECAB
//
//  Created by Raphaël Bertin on 13/07/2016.
//  Copyright © 2016 Oliver Braddick and Jan Atkinson. All rights reserved.
//

import Foundation

class VisualSustainFactory {
    
    static let practiceSequence: [GameSequence] =
        [
            GameSequence(p: .Ball),
            GameSequence(p: .Bus),
            GameSequence(p: .Boot),
            GameSequence(p: .Pig),
            GameSequence(p: .Sun),
            GameSequence(p: .Star),
            GameSequence(p: .Leaf),
            GameSequence(p: .Key),
            GameSequence(p: .Cat),
            GameSequence(p: .Bed),
            GameSequence(p: .Sock),
            GameSequence(p: .Horse),
            GameSequence(p: .Cake),
            GameSequence(p: .Boat),
            GameSequence(p: .Book),
            GameSequence(p: .Dog),
            GameSequence(p: .Car),
            GameSequence(p: .Clock),
            GameSequence(p: .Fish),
            GameSequence(p: .Train),
            GameSequence(p: .Empty)
        ]
    
    static let gameSequence: [GameSequence] =
        [
            GameSequence(p: .Sun),
            GameSequence(p: .Key),
            GameSequence(p: .Sock),
            GameSequence(p: .Boat),
            GameSequence(p: .Boot),
            GameSequence(p: .Pig),
            GameSequence(p: .Clock),
            GameSequence(p: .Car),
            GameSequence(p: .Book),
            GameSequence(p: .Door),
            GameSequence(p: .Cat),
            GameSequence(p: .Ball),
            GameSequence(p: .Bed),
            GameSequence(p: .Bus),
            GameSequence(p: .Horse),
            GameSequence(p: .Train),
            GameSequence(p: .Cake),
            GameSequence(p: .Leaf),
            GameSequence(p: .Dog),
            GameSequence(p: .Star),
            GameSequence(p: .Spoon),
            GameSequence(p: .Chair),
            GameSequence(p: .Bike),
            GameSequence(p: .Tree),
            GameSequence(p: .Fish),
            GameSequence(p: .Door),
            GameSequence(p: .Bus),
            GameSequence(p: .Ball),
            GameSequence(p: .Sun),
            GameSequence(p: .Horse),
            GameSequence(p: .Spoon),
            GameSequence(p: .Bed),
            GameSequence(p: .Leaf),
            GameSequence(p: .Boot),
            GameSequence(p: .Fish),
            GameSequence(p: .Star),
            GameSequence(p: .Cake),
            GameSequence(p: .Tree),
            GameSequence(p: .Sock),
            GameSequence(p: .Clock),
            GameSequence(p: .Book),
            GameSequence(p: .Cat),
            GameSequence(p: .Key),
            GameSequence(p: .Train),
            GameSequence(p: .Chair),
            GameSequence(p: .Pig),
            GameSequence(p: . Boat),
            GameSequence(p: .Car),
            GameSequence(p: .Bike),
            GameSequence(p: .Dog),
            GameSequence(p: .Bus),
            GameSequence(p: .Bed),
            GameSequence(p: .Sun),
            GameSequence(p: .Chair),
            GameSequence(p: .Dog),
            GameSequence(p: .Train),
            GameSequence(p: .Ball),
            GameSequence(p: .Horse),
            GameSequence(p: .Bike),
            GameSequence(p: .Leaf),
            GameSequence(p: .Sock),
            GameSequence(p: .Cake),
            GameSequence(p: .Boat),
            GameSequence(p: .Cat),
            GameSequence(p: .Key),
            GameSequence(p: .Door),
            GameSequence(p: .Tree),
            GameSequence(p: .Pig),
            GameSequence(p: .Spoon),
            GameSequence(p: .Clock),
            GameSequence(p: .Car),
            GameSequence(p: .Boot),
            GameSequence(p: .Book),
            GameSequence(p: .Fish),
            GameSequence(p: .Star),
            GameSequence(p: .Bike),
            GameSequence(p: .Clock),
            GameSequence(p: .Car),
            GameSequence(p: .Pig),
            GameSequence(p: .Boat),
            GameSequence(p: .Tree),
            GameSequence(p: .Cake),
            GameSequence(p: .Sock),
            GameSequence(p: .Bus),
            GameSequence(p: .Star),
            GameSequence(p: .Door),
            GameSequence(p: .Horse),
            GameSequence(p: .Spoon),
            GameSequence(p: .Ball),
            GameSequence(p: .Dog),
            GameSequence(p: .Boot),
            GameSequence(p: .Key),
            GameSequence(p: .Leaf),
            GameSequence(p: .Train),
            GameSequence(p: .Cat),
            GameSequence(p: .Chair),
            GameSequence(p: .Sun),
            GameSequence(p: .Bed),
            GameSequence(p: .Fish),
            GameSequence(p: .Book),
            GameSequence(p: .Cake),
            GameSequence(p: .Ball),
            GameSequence(p: .Star),
            GameSequence(p: .Bus),
            GameSequence(p: .Pig),
            GameSequence(p: .Train),
            GameSequence(p: .Boat),
            GameSequence(p: .Sun),
            GameSequence(p: .Fish),
            GameSequence(p: .Spoon),
            GameSequence(p: .Leaf),
            GameSequence(p: .Bed),
            GameSequence(p: .Dog),
            GameSequence(p: .Tree),
            GameSequence(p: .Door),
            GameSequence(p: .Boot),
            GameSequence(p: .Bike),
            GameSequence(p: .Cat),
            GameSequence(p: .Car),
            GameSequence(p: .Sock),
            GameSequence(p: .Chair),
            GameSequence(p: .Key),
            GameSequence(p: .Clock),
            GameSequence(p: .Book),
            GameSequence(p: .Horse),
            GameSequence(p: .Door),
            GameSequence(p: .Bike),
            GameSequence(p: .Car),
            GameSequence(p: .Leaf),
            GameSequence(p: .Cake),
            GameSequence(p: .Fish),
            GameSequence(p: .Bed),
            GameSequence(p: .Boot),
            GameSequence(p: .Horse),
            GameSequence(p: .Bus),
            GameSequence(p: .Train),
            GameSequence(p: .Sun),
            GameSequence(p: .Sock),
            GameSequence(p: .Chair),
            GameSequence(p: .Dog),
            GameSequence(p: .Star),
            GameSequence(p: .Ball),
            GameSequence(p: .Train),
            GameSequence(p: .Pig),
            GameSequence(p: .Key),
            GameSequence(p: .Clock),
            GameSequence(p: .Spoon),
            GameSequence(p: .Book),
            GameSequence(p: .Cat),
            GameSequence(p: .Boat),
            GameSequence(p: .Empty)
    ]
    
}